/**
 * LES AUDIT EXCEL EXPORT API
 *
 * POST /api/les/export/excel
 * Generates an Excel spreadsheet of audit results
 *
 * Security: Authenticated users only
 * Format: CSV (Excel-compatible) with detailed line items
 */

import { currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const user = await currentUser();

  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const body = await request.json();
    const { month, year, summary, flags, lineItems } = body;

    const monthName = new Date(2000, month - 1).toLocaleString("default", {
      month: "long",
    });

    // Build CSV content (Excel-compatible)
    let csvContent = "";

    // Header
    csvContent += `LES Audit Report - ${monthName} ${year}\n`;
    csvContent += `Generated: ${new Date().toLocaleString()}\n`;
    csvContent += `\n`;

    // Summary Section
    csvContent += `SUMMARY\n`;
    csvContent += `Gross Pay,$${((summary?.gross_cents || 0) / 100).toFixed(2)}\n`;
    csvContent += `Net Pay,$${((summary?.net_cents || 0) / 100).toFixed(2)}\n`;
    csvContent += `Total Taxes,$${((summary?.total_taxes_cents || 0) / 100).toFixed(2)}\n`;
    csvContent += `Total Deductions,$${((summary?.total_deductions_cents || 0) / 100).toFixed(2)}\n`;
    csvContent += `\n`;

    // Flags Section
    csvContent += `AUDIT FINDINGS (${flags?.length || 0})\n`;
    csvContent += `Severity,Code,Message,Delta\n`;
    if (flags && flags.length > 0) {
      flags.forEach((flag: any) => {
        csvContent += `${flag.severity},"${flag.flag_code}","${flag.message}",$${(flag.delta_cents / 100).toFixed(2)}\n`;
      });
    } else {
      csvContent += `No issues found,---,Your LES appears accurate,$0.00\n`;
    }
    csvContent += `\n`;

    // Line Items Section
    csvContent += `LINE ITEMS (${lineItems?.length || 0})\n`;
    csvContent += `Code,Description,Section,Amount\n`;
    if (lineItems && lineItems.length > 0) {
      lineItems.forEach((item: any) => {
        csvContent += `"${item.line_code}","${item.description}","${item.section}",$${(item.amount_cents / 100).toFixed(2)}\n`;
      });
    }
    csvContent += `\n`;

    // Footer
    csvContent += `\n`;
    csvContent += `Data Provenance: Official 2025 DFAS pay tables and JTR regulations\n`;
    csvContent += `Generated by: Garrison Ledger LES Auditor\n`;
    csvContent += `\n`;

    // Return as downloadable CSV (opens in Excel)
    return new NextResponse(csvContent, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": `attachment; filename="LES-Audit-${month}-${year}.csv"`,
      },
    });
  } catch (error) {
    console.error("Excel export error:", error);
    return NextResponse.json({ error: "Excel generation failed" }, { status: 500 });
  }
}
